apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthmate-app
  labels:
    app: healthmate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: healthmate
  template:
    metadata:
      labels:
        app: healthmate
    spec:
      containers:
        - name: healthmate
          image: manav108/healthmate:latest
          ports:
            - containerPort: 8000